"""
Loads the 4 raw CSVs (generated by generate_data.py) into a DuckDB
warehouse file, under a `raw` schema - the starting point dbt will
build on top of.
"""

import duckdb

con = duckdb.connect("warehouse.duckdb")
con.execute("CREATE SCHEMA IF NOT EXISTS raw")

tables = ["users", "events", "transactions", "experiment_assignments"]
for t in tables:
    con.execute(f"""
        CREATE OR REPLACE TABLE raw.{t} AS
        SELECT * FROM read_csv_auto('data/{t}.csv', header=True)
    """)
    count = con.execute(f"SELECT COUNT(*) FROM raw.{t}").fetchone()[0]
    print(f"raw.{t}: {count:,} rows loaded")

con.close()